### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'note.md'

### ISSUE THREAD

**Issue by metascience-lab** [WilmerWang/autoLiterature#1]
Hello~ 非常感谢你写了这个程序
我在note文件夹下新建了note.md，但使用时会出现No such file or directory: 'note.md'
```
Traceback (most recent call last):
  File "E:\autoLiterature-main\scr\autoimage.py", line 75, in <module>
    modified_files, file_md5 = folder_moniter(moniter_files)
  File "E:\autoLiterature-main\scr\autoimage.py", line 41, in folder_moniter
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
FileNotFoundError: [Errno 2] No such file or directory: '..\\note\\note.md'
Traceback (most recent call last):
  File "E:\autoLiterature-main\scr\autoliterature.py", line 82, in <module>
    modified_files, file_md5 = folder_moniter(moniter_files)
  File "E:\autoLiterature-main\scr\autoliterature.py", line 44, in folder_moniter
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
FileNotFoundError: [Errno 2] No such file or directory: 'note.md'
```

我修改了file_path为绝对路径：
`file_path = os.path.join(os.getcwd(),'note',file_path)`
但会报错：
`RuntimeError: dictionary changed size during iteration`
报错的全文如下：
```
E:\autoLiterature-main\note\note.md
Traceback (most recent call last):
  File "E:\autoLiterature-main\scr\autoimage.py", line 75, in <module>
    modified_files, file_md5 = folder_moniter(moniter_files)
  File "E:\autoLiterature-main\scr\autoimage.py", line 36, in folder_moniter
    for file_path, md5_before in file_md5.items():
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "E:\autoLiterature-main\scr\autoliterature.py", line 83, in <module>
    modified_files, file_md5 = folder_moniter(moniter_files)
  File "E:\autoLiterature-main\scr\autoliterature.py", line 43, in folder_moniter
    for file_path, md5_before in file_md5.items():
RuntimeError: dictionary changed size during iteration
```
请问我该怎么解决呢？谢谢

**Comment by wilmerwang** [comment]
@Nemo1874 你重新clone一下试试

**Comment by yawenouyang** [comment]
加入这么一行就可以了
`moniter_files = [os.path.join(root_path, moniter_file) for moniter_file in moniter_files]`

**Comment by WilmerWang** [comment]
> 加入这么一行就可以了
> `moniter_files = [os.path.join(root_path, moniter_file) for moniter_file in moniter_files]`

ok,或者你把main.py相应参数改成绝对路径哈
