### ISSUE TITLE
保存文献pdf的文件夹保存位置，以及无法替换md文档内容的问题

### ISSUE THREAD

**Issue by ZERO2ER0** [WilmerWang/autoLiterature#10]
Traceback (most recent call last):
  File "/Users/lichen/Documents/autoLiterature/scr/autoliterature.py", line 95, in <module>
    main()
  File "/Users/lichen/Documents/autoLiterature/scr/autoliterature.py", line 38, in main
    modified_items = folder_moniter.file_md5_update()
  File "/Users/lichen/Documents/autoLiterature/scr/modules.py", line 52, in file_md5_update
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
IsADirectoryError: [Errno 21] Is a directory: '/Users/lichen/Dropbox/Apps/PaparsUpdate/pdf'
Traceback (most recent call last):
  File "/Users/lichen/Documents/autoLiterature/scr/autoimage.py", line 71, in <module>
    main()
  File "/Users/lichen/Documents/autoLiterature/scr/autoimage.py", line 37, in main
    modified_items = folder_moniter.file_md5_update()
  File "/Users/lichen/Documents/autoLiterature/scr/modules.py", line 52, in file_md5_update
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
IsADirectoryError: [Errno 21] Is a directory: '/Users/lichen/Dropbox/Apps/PaparsUpdate/pdf'

**Comment by wilmerwang** [comment]
你好，pdf文件夹和md文件夹是并列的关系，不要成包含关系。比如

/Dropbox/mds/
/Dropbox/pdfs/

其中mds文件夹中仅放*.md文件，也就是你的论文笔记
