### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte

### ISSUE THREAD

**Issue by wenqian-ye** [WilmerWang/autoLiterature#2]
作者您好 非常感谢分享这个脚本以及持续更新！

在之前版本中  根据 #1 **更改文件路径**之后可以正常运行。
最新更新的版本运行之后出现了以上错误。以下为报错信息：

```
Traceback (most recent call last):
  File "/Users/-/Dropbox/autoLiterature/scr/autoliterature.py", line 72, in <module>
    main()
  File "/Users/-/Dropbox/autoLiterature/scr/autoliterature.py", line 38, in main
    modified_items = folder_moniter.file_md5_update()
  File "/Users/-/Dropbox/autoLiterature/scr/modules.py", line 52, in file_md5_update
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
  File "/Users/-/opt/anaconda3/envs/autoliter/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte
Traceback (most recent call last):
  File "/Users/-/Dropbox/autoLiterature/scr/autoimage.py", line 68, in <module>
    main()
  File "/Users/-/Dropbox/autoLiterature/scr/autoimage.py", line 37, in main
    modified_items = folder_moniter.file_md5_update()
  File "/Users/-/Dropbox/autoLiterature/scr/modules.py", line 52, in file_md5_update
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
  File "/Users/-/opt/anaconda3/envs/autoliter/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte
```

**Comment by wilmerwang** [comment]
@wenqian-ye 很可能是中文的问题，我强烈建议你使用V2版本，也就是目前的版本，更方便快捷，能够识别所有DOI和arxiv ID。

**Comment by wenqian-ye** [comment]
7/4更新之后问题解决了
