### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

### ISSUE THREAD

**Issue by cntommy** [WilmerWang/autoLiterature#6]
请问运行python main.py之后报错是为什么呢，之前已经成功运行过了（虽然运行了之后不会自动替换文献的信息）

`Traceback (most recent call last):
  File "/Users/gaolegao/Applications/autoLiterature/scr/autoliterature.py", line 95, in <module>
    main()
  File "/Users/gaolegao/Applications/autoLiterature/scr/autoliterature.py", line 38, in main
    modified_items = folder_moniter.file_md5_update()
  File "/Users/gaolegao/Applications/autoLiterature/scr/modules.py", line 52, in file_md5_update
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
  File "/opt/anaconda3/envs/autoliter/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
Traceback (most recent call last):
  File "/Users/gaolegao/Applications/autoLiterature/scr/autoimage.py", line 71, in <module>
    main()
  File "/Users/gaolegao/Applications/autoLiterature/scr/autoimage.py", line 37, in main
    modified_items = folder_moniter.file_md5_update()
  File "/Users/gaolegao/Applications/autoLiterature/scr/modules.py", line 52, in file_md5_update
    md5_now = hashlib.md5(open(file_path).read().encode('utf-8')).hexdigest()
  File "/opt/anaconda3/envs/autoliter/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte`

**Comment by wilmerwang** [comment]
@cntommy 是不是因为监测的路径有中文，或者空格，或者其它？建议你用英文路径试一下

**Comment by cntommy** [comment]
@WilmerWang 路径都是英文的（如下），就很奇怪，有没有可能和python的版本有关？
`/Users/gaolegao/Applications/autoLiterature/note`

**Comment by wilmerwang** [comment]
open(file_path).read().encode('utf-8') 这一步出了问题，或许你文件夹下有其它编码的文件，比如mac 经常会出现 .DO* 隐藏文件。或许你可以查看一下/Users/gaolegao/Applications/autoLiterature/note 文件夹下文件
